version: '3.8'
services:
  # Database Configuration
  database:
    restart: always
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/postgress/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"